-- =====================================================
-- SISTEM AKUNTANSI PERSEDIAAN TOKO MAINAN
-- DATABASE PostgreSQL / SUPABASE
-- =====================================================


-- =====================================================
-- 1. TABEL BARANG
-- =====================================================

CREATE TABLE IF NOT EXISTS barang (

    id_barang BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    kode_barang VARCHAR(20)
        NOT NULL
        UNIQUE,

    nama_barang VARCHAR(100)
        NOT NULL,

    kategori VARCHAR(50)
        NOT NULL,

    satuan VARCHAR(20)
        NOT NULL,

    harga_beli NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    harga_jual NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    stok INTEGER
        NOT NULL
        DEFAULT 0,

    stok_minimum INTEGER
        NOT NULL
        DEFAULT 0,

    CONSTRAINT cek_harga_beli
        CHECK (harga_beli >= 0),

    CONSTRAINT cek_harga_jual
        CHECK (harga_jual >= 0),

    CONSTRAINT cek_stok
        CHECK (stok >= 0),

    CONSTRAINT cek_stok_minimum
        CHECK (stok_minimum >= 0)
);


-- =====================================================
-- 2. TABEL PEMASOK
-- =====================================================

CREATE TABLE IF NOT EXISTS pemasok (

    id_pemasok BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    kode_pemasok VARCHAR(20)
        NOT NULL
        UNIQUE,

    nama_pemasok VARCHAR(100)
        NOT NULL,

    alamat TEXT,

    no_telepon VARCHAR(20)
);


-- =====================================================
-- 3. TABEL PELANGGAN
-- =====================================================

CREATE TABLE IF NOT EXISTS pelanggan (

    id_pelanggan BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    kode_pelanggan VARCHAR(20)
        NOT NULL
        UNIQUE,

    nama_pelanggan VARCHAR(100)
        NOT NULL,

    alamat TEXT,

    no_telepon VARCHAR(20)
);


-- =====================================================
-- 4. TABEL PEMBELIAN
-- =====================================================

CREATE TABLE IF NOT EXISTS pembelian (

    id_pembelian BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nomor_pembelian VARCHAR(30)
        NOT NULL
        UNIQUE,

    tanggal_pembelian DATE
        NOT NULL,

    id_pemasok BIGINT
        NOT NULL,

    total_pembelian NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    CONSTRAINT fk_pembelian_pemasok
        FOREIGN KEY (id_pemasok)
        REFERENCES pemasok(id_pemasok),

    CONSTRAINT cek_total_pembelian
        CHECK (total_pembelian >= 0)
);


-- =====================================================
-- 5. DETAIL PEMBELIAN
-- =====================================================

CREATE TABLE IF NOT EXISTS detail_pembelian (

    id_detail_pembelian BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    id_pembelian BIGINT
        NOT NULL,

    id_barang BIGINT
        NOT NULL,

    jumlah INTEGER
        NOT NULL,

    harga_beli NUMERIC(15,2)
        NOT NULL,

    subtotal NUMERIC(15,2)
        NOT NULL,

    CONSTRAINT fk_detail_pembelian
        FOREIGN KEY (id_pembelian)
        REFERENCES pembelian(id_pembelian)
        ON DELETE CASCADE,

    CONSTRAINT fk_detail_barang_pembelian
        FOREIGN KEY (id_barang)
        REFERENCES barang(id_barang),

    CONSTRAINT cek_jumlah_pembelian
        CHECK (jumlah > 0),

    CONSTRAINT cek_harga_beli_detail
        CHECK (harga_beli >= 0),

    CONSTRAINT cek_subtotal_pembelian
        CHECK (subtotal >= 0)
);


-- =====================================================
-- 6. TABEL PENJUALAN
-- =====================================================

CREATE TABLE IF NOT EXISTS penjualan (

    id_penjualan BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nomor_penjualan VARCHAR(30)
        NOT NULL
        UNIQUE,

    tanggal_penjualan DATE
        NOT NULL,

    id_pelanggan BIGINT,

    total_penjualan NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    CONSTRAINT fk_penjualan_pelanggan
        FOREIGN KEY (id_pelanggan)
        REFERENCES pelanggan(id_pelanggan),

    CONSTRAINT cek_total_penjualan
        CHECK (total_penjualan >= 0)
);


-- =====================================================
-- 7. DETAIL PENJUALAN
-- =====================================================

CREATE TABLE IF NOT EXISTS detail_penjualan (

    id_detail_penjualan BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    id_penjualan BIGINT
        NOT NULL,

    id_barang BIGINT
        NOT NULL,

    jumlah INTEGER
        NOT NULL,

    harga_jual NUMERIC(15,2)
        NOT NULL,

    subtotal NUMERIC(15,2)
        NOT NULL,

    CONSTRAINT fk_detail_penjualan
        FOREIGN KEY (id_penjualan)
        REFERENCES penjualan(id_penjualan)
        ON DELETE CASCADE,

    CONSTRAINT fk_detail_barang_penjualan
        FOREIGN KEY (id_barang)
        REFERENCES barang(id_barang),

    CONSTRAINT cek_jumlah_penjualan
        CHECK (jumlah > 0),

    CONSTRAINT cek_harga_jual_detail
        CHECK (harga_jual >= 0),

    CONSTRAINT cek_subtotal_penjualan
        CHECK (subtotal >= 0)
);


-- =====================================================
-- DATA CONTOH BARANG
-- =====================================================

INSERT INTO barang
(
    kode_barang,
    nama_barang,
    kategori,
    satuan,
    harga_beli,
    harga_jual,
    stok,
    stok_minimum
)
VALUES
(
    'BRG001',
    'Mobil-Mobilan',
    'Kendaraan',
    'Unit',
    25000,
    40000,
    20,
    5
),
(
    'BRG002',
    'Boneka Beruang',
    'Boneka',
    'Unit',
    35000,
    55000,
    15,
    5
),
(
    'BRG003',
    'Puzzle Anak',
    'Edukasi',
    'Unit',
    20000,
    35000,
    10,
    3
)
ON CONFLICT (kode_barang)
DO NOTHING;


-- =====================================================
-- DATA CONTOH PEMASOK
-- =====================================================

INSERT INTO pemasok
(
    kode_pemasok,
    nama_pemasok,
    alamat,
    no_telepon
)
VALUES
(
    'SUP001',
    'PT Mainan Ceria',
    'Semarang',
    '081234567890'
)
ON CONFLICT (kode_pemasok)
DO NOTHING;


-- =====================================================
-- DATA CONTOH PELANGGAN
-- =====================================================

INSERT INTO pelanggan
(
    kode_pelanggan,
    nama_pelanggan,
    alamat,
    no_telepon
)
VALUES
(
    'PLG001',
    'Pelanggan Umum',
    '-',
    '-'
)
ON CONFLICT (kode_pelanggan)
DO NOTHING;

-- =====================================================
-- 8. TABEL AKUN
-- =====================================================

CREATE TABLE IF NOT EXISTS public.akun (

    id_akun BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    kode_akun VARCHAR(20)
        NOT NULL
        UNIQUE,

    nama_akun VARCHAR(100)
        NOT NULL,

    jenis_akun VARCHAR(30)
        NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT NOW(),

    CONSTRAINT cek_jenis_akun
        CHECK (
            jenis_akun IN (
                'ASET',
                'KEWAJIBAN',
                'EKUITAS',
                'PENDAPATAN',
                'BEBAN'
            )
        )
);


-- =====================================================
-- 9. DATA AKUN
-- =====================================================

INSERT INTO public.akun
(
    kode_akun,
    nama_akun,
    jenis_akun
)
VALUES
(
    '1-1000',
    'Kas',
    'ASET'
),
(
    '1-1100',
    'Persediaan Barang',
    'ASET'
),
(
    '1-1200',
    'Piutang Usaha',
    'ASET'
),
(
    '2-1000',
    'Utang Usaha',
    'KEWAJIBAN'
),
(
    '3-1000',
    'Modal',
    'EKUITAS'
),
(
    '4-1000',
    'Penjualan',
    'PENDAPATAN'
),
(
    '5-1000',
    'Harga Pokok Penjualan',
    'BEBAN'
),
(
    '5-1100',
    'Beban Penyesuaian Persediaan',
    'BEBAN'
)
ON CONFLICT (kode_akun)
DO NOTHING;


-- =====================================================
-- 10. TABEL JURNAL UMUM
-- =====================================================

CREATE TABLE IF NOT EXISTS public.jurnal_umum (

    id_jurnal BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    tanggal_jurnal DATE
        NOT NULL,

    nomor_bukti VARCHAR(30)
        NOT NULL,

    sumber_transaksi VARCHAR(30)
        NOT NULL,

    id_akun BIGINT
        NOT NULL,

    keterangan TEXT
        NOT NULL,

    debit NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    kredit NUMERIC(15,2)
        NOT NULL
        DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT NOW(),

    CONSTRAINT fk_jurnal_akun
        FOREIGN KEY (id_akun)
        REFERENCES public.akun(id_akun),

    CONSTRAINT cek_debit_kredit
        CHECK (
            debit >= 0
            AND kredit >= 0
        ),

    CONSTRAINT cek_satu_sisi
        CHECK (
            NOT (
                debit > 0
                AND kredit > 0
            )
        )
);


-- =====================================================
-- 11. INDEX JURNAL
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_jurnal_tanggal
ON public.jurnal_umum(tanggal_jurnal);

CREATE INDEX IF NOT EXISTS idx_jurnal_nomor_bukti
ON public.jurnal_umum(nomor_bukti);

CREATE INDEX IF NOT EXISTS idx_jurnal_akun
ON public.jurnal_umum(id_akun);


-- =====================================================
-- 12. RLS AKUN
-- =====================================================

ALTER TABLE public.akun ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_akun"
ON public.akun;

CREATE POLICY "anon_select_akun"
ON public.akun
FOR SELECT
TO anon
USING (true);


-- =====================================================
-- 13. RLS JURNAL UMUM
-- =====================================================

ALTER TABLE public.jurnal_umum ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_jurnal_umum"
ON public.jurnal_umum;

CREATE POLICY "anon_select_jurnal_umum"
ON public.jurnal_umum
FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "anon_insert_jurnal_umum"
ON public.jurnal_umum;

CREATE POLICY "anon_insert_jurnal_umum"
ON public.jurnal_umum
FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_jurnal_umum"
ON public.jurnal_umum;

CREATE POLICY "anon_update_jurnal_umum"
ON public.jurnal_umum
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_jurnal_umum"
ON public.jurnal_umum;

CREATE POLICY "anon_delete_jurnal_umum"
ON public.jurnal_umum
FOR DELETE
TO anon
USING (true);